### PR TITLE
Active link to new main

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**
I have closed the previous branch as it was out of sync with main and I have added the navbar commits to this new branch. 

I have also fixed the navbar according to your 2 comments @tomaroberts which were:

1) change bg color
2) put edit profile and logout at the end of the tab

I attach 2 screenshots to show the changes and also that active link is working
Screenshot 2023-03-10 at 07 41 12
Screenshot 2023-03-10 at 07 41 19

### CODE REVIEW

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts, @heyhaleema, this is now ready for review

**Comment by heyhaleema** [comment]
@Lucrezia-Cester I've just had a quick test of this and the core functionality works, but I just have a few notes/questions:

- Is the Login tab also meant to change colour when you select on it or only the tabs when you're already logged in?
- It seems to render differently for me i.e., the navbar is a different colour:
   

   https://user-images.githubusercontent.com/67117138/227531965-0e860d2a-3f00-47cb-a33f-c72652558e48.mov

**Comment by Lucrezia-Cester** [comment]
Hi @heyhaleema, I just opened this PR (active_link_to_new_main) with github desktop and I get the correct results --> see attached pics. Could it be that you opened the old branch for the issue?
Screenshot 2023-03-24 at 13 39 41
Screenshot 2023-03-24 at 13 39 44
Screenshot 2023-03-24 at 13 39 49

**Review by heyhaleema — APPROVED** [review]
Thanks, @Lucrezia-Cester, this now works as expected. LGTM 👍

**Pull request merged**
