### PR TITLE
added active link to the navbar items

### PR DESCRIPTION
**Pull request by Lucrezia-Cester**

### CODE REVIEW

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts, could you review this PR please?

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts, I noticed you changed the branch from main to staging. Is there anything else that should be changed in this PR before merging?

**Review by tomaroberts — CHANGES_REQUESTED** [review]
@Lucrezia-Cester 

hazen-web-app-navbar

Why have you moved the navbar to the left hand side and given it a dark background? It doesn't look good against the rest of the light website. Can you move the navbar back to where it was originally and keep the original colour scheme please?

To set active links, I don't think you need to adjust the background. It should just be a text property with HTML I think.

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts, I want to merge this PR into a branch that I just branched off the main branch so that I can use the dockerised version of the web app and it doesn't take me 10 min to just start the hazen web app. I will then open a PR for this issue again.

**Pull request merged**
