### PR TITLE
NHS branding

### PR DESCRIPTION
**Pull request by mollybuckley**
Redesigning some of the visual elements to be more in agreement with the NHS identity guidelines: https://www.england.nhs.uk/nhsidentity/identity-guidelines/

### CODE REVIEW

**Comment by Biaaaaaa12** [comment]
Looks good! 
Small suggestion for further work would be to change the color of the links to the same blue. ( can take a look at this myself )

**Review by Biaaaaaa12 — APPROVED** [review]
looks great!

**Comment by mollybuckley** [comment]
Thanks for reviewing @Biaaaaaa12 - are you happy for this to be merged for now and we can open a new PR for your suggested improvements + any further ones?

**Comment by Biaaaaaa12** [comment]
Yes definitely!

**Pull request merged**
